[package]
name = "apprenderer"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
image = "0.25.6"
skia-safe = { version="0.87.0", features=[ 'vulkan' ]}
vulkano = "0.35.1"
winit = "0.30.12"
